<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {useRouter} from 'vue-router'
import {api,type Envelope} from '@/api'
import {useAuthStore} from '@/stores/auth'
const props=defineProps<{type:'EXAM'|'EVALUATION'}>()
const router=useRouter(),auth=useAuthStore(),batches=ref<any[]>([]),selected=ref<any>(),loading=ref(false),detailLoading=ref(false)
const keyword=ref(''),batchStatusFilter=ref(''),rowStatus=ref(''),importVisible=ref(false),editVisible=ref(false),file=ref<File>(),editRowData=ref<any>({}),editRowId=ref<number>(),editRowType=ref('')
const meta=reactive({examName:'',examDate:'',remark:'',summaryType:'MONTH',periodKey:''})
const canPublish=computed(()=>['ADMIN','SUPER_ADMIN'].includes(auth.user?.role||'')),title=computed(()=>props.type==='EXAM'?'历史成绩导入':'历史评价导入')
const rows=computed(()=>selected.value?.rows||[]),filteredRows=computed(()=>rows.value.filter((r:any)=>{const q=keyword.value.trim().toLowerCase(),raw=String(r.raw_json||'').toLowerCase();return(!q||((r.employee_no||'')+' '+raw).toLowerCase().includes(q))&&(!rowStatus.value||r.state===rowStatus.value)}))
const completedCount=computed(()=>rows.value.filter((r:any)=>r.row_type==='EXAM_RESULT'&&raw(r).resultStatus==='COMPLETED').length),absentCount=computed(()=>rows.value.filter((r:any)=>r.row_type==='EXAM_RESULT'&&raw(r).resultStatus==='ABSENT').length)
const stateLabel=(s:string)=>s==='ERROR'?'错误':s==='WARNING'?'警告':'通过',stateType=(s:string)=>s==='ERROR'?'danger':s==='WARNING'?'warning':'success'
const batchStatus=(s:string)=>({DRAFT:'草稿',SUBMITTED:'待审核',PUBLISHED:'已发布',SUPERSEDED:'已被修订',REVOKED:'已撤销'} as any)[s]||s
async function load(){loading.value=true;try{batches.value=(await api.get<any,Envelope<any[]>>('/history-imports',{params:{type:props.type,size:200}})).data||[]}finally{loading.value=false}}
async function open(id:number){detailLoading.value=true;try{selected.value=(await api.get<any,Envelope<any>>('/history-imports/'+id)).data}finally{detailLoading.value=false}}
async function downloadTemplate(){const blob=await api.get<any,Blob>('/history-imports/templates',{params:{type:props.type},responseType:'blob'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=title.value+'模板.xlsx';a.click();URL.revokeObjectURL(url)}
function openImport(){Object.assign(meta,{examName:'',examDate:'',remark:'',summaryType:'MONTH',periodKey:''});file.value=undefined;importVisible.value=true}
function chooseFile(f:File){file.value=f;return false}
async function submitImport(){if(!file.value)return ElMessage.warning('请先选择 Excel 文件');if(props.type==='EXAM'&&(!meta.examName.trim()||!meta.examDate))return ElMessage.warning('请填写考试名称和考试日期');if(props.type==='EVALUATION'&&(!meta.summaryType||!meta.periodKey))return ElMessage.warning('请填写评价类型和期间');const form=new FormData();form.append('type',props.type);form.append('metadata',JSON.stringify(meta));form.append('file',file.value);const result=(await api.post<any,Envelope<any>>('/history-imports',form)).data;importVisible.value=false;ElMessage.success(result.rowCount+' 行，错误 '+result.errorCount+' 条，已创建草稿');await load();await open(result.batchId)}
function raw(row:any){try{return JSON.parse(row.raw_json||'{}')}catch{return {}}}
function edit(row:any){editRowId.value=row.id;editRowType.value=row.row_type;editRowData.value={...raw(row)};editVisible.value=true}
async function saveEdit(){if(!selected.value||!editRowId.value)return;await api.put('/history-imports/'+selected.value.id+'/rows/'+editRowId.value,editRowData.value);editVisible.value=false;ElMessage.success('已保存并重新校验');await open(selected.value.id);await load()}
async function validate(){if(!selected.value)return;await api.post('/history-imports/'+selected.value.id+'/validate');ElMessage.success('已重新校验');await open(selected.value.id);await load()}
async function submit(){if(!selected.value)return;await api.post('/history-imports/'+selected.value.id+'/submit');ElMessage.success('已提交管理员审核');await open(selected.value.id);await load()}
async function publish(){if(!selected.value)return;await ElMessageBox.confirm('确认无误并正式生效？发布后当前批次只读。','确认发布',{type:'warning'});await api.post('/history-imports/'+selected.value.id+'/publish');ElMessage.success('历史数据已生效');await open(selected.value.id);await load()}
async function revision(){if(!selected.value)return;await ElMessageBox.confirm('将复制完整批次为新的可编辑修订版本，原版本保持可追溯。继续吗？','创建修订',{type:'warning'});const result=(await api.post<any,Envelope<any>>('/history-imports/'+selected.value.id+'/revision')).data;ElMessage.success('已创建修订草稿');await load();await open(result.batchId)}
async function revoke(){if(!selected.value)return;await ElMessageBox.confirm('撤销后该批次数据将不再对业务页面可见。确认撤销吗？','撤销批次',{type:'warning'});await api.post('/history-imports/'+selected.value.id+'/revoke');ElMessage.success('批次已撤销');await open(selected.value.id);await load()}
onMounted(load)
</script>
<template><div class="history-workbench">
<header class="page-head"><div><span class="eyebrow">{{props.type==='EXAM'?'考试成绩':'综合评价'}} · 历史导入</span><h1>{{title}}</h1><p>先解析预览，再确认生效；已发布记录通过修订版本修改。</p></div><div class="head-actions"><el-button @click="router.back()">返回</el-button><el-button @click="downloadTemplate">下载模板</el-button><el-button type="primary" @click="openImport">导入{{props.type==='EXAM'?'历史成绩':'历史评价'}}</el-button></div></header>
<div class="history-layout"><el-card class="batch-card"><template #header><div class="card-head"><strong>历史导入记录</strong><el-button link @click="load">刷新</el-button></div></template><div class="filters"><el-input v-model="keyword" clearable placeholder="考试/文件/编号/工号"/><el-select v-model="batchStatusFilter" filterable clearable placeholder="批次状态"><el-option label="草稿" value="DRAFT"/><el-option label="待审核" value="SUBMITTED"/><el-option label="已发布" value="PUBLISHED"/><el-option label="已修订" value="SUPERSEDED"/><el-option label="已撤销" value="REVOKED"/></el-select></div><el-table :data="batches.filter((b:any)=>(!batchStatusFilter||b.status===batchStatusFilter)&&(!keyword||((b.exam_name||'')+' '+(b.original_filename||'')+' '+(b.generated_exam_key||'')).toLowerCase().includes(keyword.toLowerCase())))" v-loading="loading" row-key="id" highlight-current-row @row-click="(row:any)=>open(row.id)"><el-table-column prop="id" label="#" width="58"/><el-table-column :label="props.type==='EXAM'?'考试名称':'期间'" min-width="125" show-overflow-tooltip><template #default="s">{{props.type==='EXAM'?s.row.exam_name:(s.row.period_key||'综合评价')}}</template></el-table-column><el-table-column prop="row_count" label="行数" width="62"/><el-table-column label="状态" width="88"><template #default="s"><el-tag effect="plain">{{batchStatus(s.row.status)}}</el-tag></template></el-table-column><el-table-column prop="created_at" label="创建时间" width="148"/></el-table><el-empty v-if="!loading&&!batches.length" description="暂无导入记录"/></el-card>
<el-card class="detail-card" v-loading="detailLoading"><template #header><div class="card-head"><strong>导入预览</strong><div v-if="selected" class="detail-actions"><el-button @click="validate" :disabled="!['DRAFT','SUBMITTED'].includes(selected.status)">重新校验</el-button><el-button @click="submit" type="primary" plain :disabled="selected.error_count>0||!['DRAFT','SUBMITTED'].includes(selected.status)">提交审核</el-button><el-button v-if="canPublish" @click="publish" type="success" :disabled="selected.error_count>0||!['DRAFT','SUBMITTED'].includes(selected.status)">确认生效</el-button><el-button v-if="canPublish&&selected.status==='PUBLISHED'" @click="revision">创建修订</el-button><el-button v-if="canPublish&&selected.status==='PUBLISHED'" @click="revoke" type="danger" plain>撤销</el-button></div></div></template><el-empty v-if="!selected" description="请选择左侧导入批次"/><template v-else><div class="meta-grid"><span>名称/期间 <b>{{selected.exam_name||selected.period_key||'综合评价'}}</b></span><span v-if="selected.exam_date">考试日期 <b>{{selected.exam_date}}</b></span><span v-if="selected.score_month">成绩月份 <b>{{selected.score_month}}</b></span><span v-if="selected.generated_exam_key">系统编号 <b>{{selected.generated_exam_key}}</b></span><span>总行数 <b>{{selected.row_count}}</b></span><span v-if="props.type==='EXAM'">已完成 <b>{{completedCount}}</b></span><span v-if="props.type==='EXAM'">缺考 <b>{{absentCount}}</b></span><span>错误 <b class="bad">{{selected.error_count}}</b></span><span>警告 <b class="warn">{{selected.warning_count}}</b></span></div><el-alert v-if="selected.status==='PUBLISHED'" title="已发布批次只读；如需调整请创建修订版本。" type="success" :closable="false"/><div class="row-toolbar"><el-input v-model="keyword" clearable placeholder="按工号、姓名模糊搜索" style="width:240px"/><el-select v-model="rowStatus" filterable clearable placeholder="行校验状态" style="width:140px"><el-option label="错误" value="ERROR"/><el-option label="警告" value="WARNING"/><el-option label="通过" value="VALID"/></el-select></div><el-table :data="filteredRows" height="540" stripe><el-table-column prop="row_no" label="行号" width="65"/><el-table-column prop="employee_no" label="工号" width="110"/><el-table-column prop="row_type" label="数据类型" width="150"/><el-table-column label="校验状态" width="90"><template #default="s"><el-tag :type="stateType(s.row.state)" effect="plain">{{stateLabel(s.row.state)}}</el-tag></template></el-table-column><el-table-column prop="error_message" label="错误" min-width="210" show-overflow-tooltip/><el-table-column prop="warning_message" label="警告" min-width="210" show-overflow-tooltip/><el-table-column label="操作" width="70"><template #default="s"><el-button link type="primary" :disabled="selected.status==='PUBLISHED'" @click="edit(s.row)">修改</el-button></template></el-table-column></el-table></template></el-card></div>
<el-dialog v-model="importVisible" :title="title" width="560px" destroy-on-close><el-form label-width="94px"><template v-if="props.type==='EXAM'"><el-form-item label="考试名称" required><el-input v-model="meta.examName" maxlength="255"/></el-form-item><el-form-item label="考试日期" required><el-date-picker v-model="meta.examDate" value-format="YYYY-MM-DD" type="date" style="width:100%"/></el-form-item><el-form-item label="成绩月份"><el-input :model-value="meta.examDate?meta.examDate.slice(0,7):''" disabled/></el-form-item></template><template v-else><el-form-item label="评价类型" required><el-select v-model="meta.summaryType" filterable style="width:100%"><el-option label="月度评价" value="MONTH"/><el-option label="季度评价" value="QUARTER"/></el-select></el-form-item><el-form-item label="评价期间" required><el-input v-model="meta.periodKey" placeholder="如 2026-09 或 2026-Q3"/></el-form-item></template><el-form-item label="备注"><el-input v-model="meta.remark" type="textarea" maxlength="1000"/></el-form-item><el-form-item label="Excel 文件" required><el-upload :show-file-list="false" :before-upload="chooseFile" accept=".xlsx,.xls"><el-button>选择文件</el-button><span class="file-name">{{file?.name||'未选择文件'}}</span></el-upload></el-form-item></el-form><template #footer><el-button @click="importVisible=false">取消</el-button><el-button type="primary" @click="submitImport">上传并预览</el-button></template></el-dialog>
<el-dialog v-model="editVisible" title="修改导入行" width="620px" destroy-on-close><el-form label-width="100px"><el-form-item label="工号"><el-input v-model="editRowData.employeeNo"/></el-form-item><el-form-item label="姓名"><el-input v-model="editRowData.employeeName"/></el-form-item><template v-if="editRowType==='EXAM_RESULT'"><el-form-item label="成绩"><el-input v-model="editRowData.score" placeholder="留空表示缺考"/></el-form-item></template><template v-else><el-form-item v-for="key in ['summaryType','periodKey','finalScore','componentCode','sourceKey','sourceName','rawScore','maxScore','weight','weightedScore','evaluatorName','comment']" :key="key" :label="key"><el-input v-model="editRowData[key]"/></el-form-item></template></el-form><template #footer><el-button @click="editVisible=false">取消</el-button><el-button type="primary" @click="saveEdit">保存并校验</el-button></template></el-dialog>
</div></template>
<style scoped>.history-workbench{padding:26px 28px;background:#f6f8fb;min-height:calc(100vh - 64px)}.page-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:18px}.eyebrow{font-size:12px;color:#3678c7;font-weight:700}.page-head h1{margin:7px 0 0;color:#263247;font-size:25px}.page-head p{margin:7px 0 0;color:#7d899a;font-size:13px}.head-actions,.detail-actions,.filters,.row-toolbar{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.history-layout{display:grid;grid-template-columns:minmax(360px,.85fr) minmax(560px,1.65fr);gap:16px}.batch-card,.detail-card{border:1px solid #e5eaf1}.card-head{display:flex;justify-content:space-between;align-items:center}.filters{margin-bottom:12px}.filters .el-input{flex:1}.meta-grid{display:flex;gap:18px;flex-wrap:wrap;padding-bottom:14px;color:#7d899a;font-size:13px}.meta-grid b{color:#263247;margin-left:4px}.meta-grid .bad{color:#e05260}.meta-grid .warn{color:#d88a1d}.detail-card :deep(.el-alert){margin-bottom:12px}.row-toolbar{justify-content:flex-end;margin-bottom:10px}.file-name{margin-left:10px;color:#7d899a}@media(max-width:1100px){.page-head{flex-direction:column}.history-layout{grid-template-columns:1fr}}@media(max-width:640px){.history-workbench{padding:16px}.head-actions>*{width:100%}.detail-actions{justify-content:flex-start}}</style>
