package com.talent.platform.user;

import com.talent.platform.common.*;import com.talent.platform.security.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.security.SecureRandom;import java.util.*;

@RestController @RequestMapping("/api/v1/users")
public class UserController {
  private static final List<String> OPS_ROLES=List.of("MENTOR","STATION_MANAGER","TRAINING_ADMIN");
  private static final List<String> SYSTEM_ROLES=List.of("ADMIN","SUPER_ADMIN");
  private static final List<String> CHANGE_ROLES=List.of("EMPLOYEE","MENTOR","TRAINING_ADMIN","ADMIN","SUPER_ADMIN");
  private final JdbcTemplate db;private final PasswordEncoder encoder;private final PermissionService permissions;private final AuditService audit;private final SecureRandom random=new SecureRandom();public UserController(JdbcTemplate db,PasswordEncoder encoder,PermissionService permissions,AuditService audit){this.db=db;this.encoder=encoder;this.permissions=permissions;this.audit=audit;}
  public record UserRequest(@NotBlank String username,@NotBlank String displayName,@Pattern(regexp="MENTOR|STATION_MANAGER|TRAINING_ADMIN|ADMIN") String role,List<Long> stationIds){}
  public record EnableRequest(boolean enabled){}
  public record DisplayNameRequest(@NotBlank String displayName){}
  public record UsernameRequest(@NotBlank @Size(max=64) @Pattern(regexp="[A-Za-z0-9._-]+",message="用户名仅支持字母、数字、点、下划线和连字符") String username){}
  public record BulkSelection(String mode,List<Long> ids,Map<String,Object> filters,List<Long> excludedIds){}
  public record BulkRequest(BulkSelection selection,Map<String,Object> changes,boolean syncLinkedEmployeeStatus,Integer expectedCount,String selectionHash,String requestId){}
  @GetMapping
  public ApiResponse<List<Map<String,Object>>> list(@RequestParam(required=false) String role) {
    permissions.require(Permissions.USER_EMPLOYEE_MANAGE);
    var allowed = allowedRoles(SecurityUtils.current());
    if (role != null && !allowed.contains(role)) return ApiResponse.ok(List.of());
    String marks = String.join(",", Collections.nCopies(allowed.size(), "?"));
    var args = new ArrayList<Object>(allowed);
    String where = " where u.role in (" + marks + ")";
    if (role != null) { where += " and u.role=?"; args.add(role); }
    return ApiResponse.ok(db.queryForList("""
        select u.id,u.username,u.display_name,u.role,u.enabled,u.must_change_password,
               u.created_at,u.avatar_token,(e.id is not null) has_employee_profile,
               e.id employee_id,e.employee_no,e.name employee_name,
               e.batch_id,b.name batch_name,e.business_unit_id,bu.name business_unit_name,
               e.class_id,cls.label class_name,ss.station_ids,ss.station_names
        from sys_user u
        left join employee e on e.user_id=u.id
        left join talent_batch b on b.id=e.batch_id
        left join business_unit bu on bu.id=e.business_unit_id
        left join dictionary_item cls on cls.id=e.class_id and cls.type_code='CLASS'
        left join (
          select sms.user_id,group_concat(sms.station_id order by sms.station_id) station_ids,
                 group_concat(s.name order by s.name separator '、') station_names
          from station_manager_scope sms
          left join service_station s on s.id=sms.station_id
          group by sms.user_id
        ) ss on ss.user_id=u.id
        """ + where + " order by u.id desc", args.toArray()));
  }
  @PostMapping("/bulk/preview") public ApiResponse<Map<String,Object>> bulkPreview(@RequestBody BulkRequest request){validateBulkRequest(request);permissions.require(Permissions.USER_EMPLOYEE_MANAGE);var ids=resolveBulkIds(request.selection());validateBulkChanges(ids,request);var versions=userVersions(ids);var operationId=UUID.randomUUID().toString();return ApiResponse.ok(Map.of("operationId",operationId,"selectionHash",selectionHash(versions),"matched",ids.size(),"changed",countChanged(ids,request.changes()),"unchanged",ids.size()-countChanged(ids,request.changes()),"blocked",List.of(),"status","PREVIEWED"));}
  @PostMapping("/bulk/execute") @Transactional public ApiResponse<Map<String,Object>> bulkExecute(@RequestBody BulkRequest request){validateBulkRequest(request);permissions.require(Permissions.USER_EMPLOYEE_MANAGE);ensureRequestNotUsed(request.requestId(),"BULK_UPDATE_USERS");var ids=resolveBulkIds(request.selection());validateBulkChanges(ids,request);var versions=userVersions(ids);if(request.expectedCount()!=null&&request.expectedCount()!=ids.size())throw new BusinessException(409,"账号筛选结果已变化，请重新预览");if(request.selectionHash()!=null&&!request.selectionHash().equals(selectionHash(versions)))throw new BusinessException(409,"账号数据已变化，请重新预览");var operationId=UUID.randomUUID().toString();int changed=0;for(Long id:ids)if(updateBulkUser(id,request))changed++;audit.logWithRequestId(request.requestId(),"BULK_UPDATE_USERS","USER",null,Map.of("operationId",operationId,"ids",ids,"count",ids.size()),Map.of("operationId",operationId,"changes",request.changes(),"changed",changed));return ApiResponse.ok(Map.of("operationId",operationId,"matched",ids.size(),"changed",changed,"unchanged",ids.size()-changed,"blocked",List.of(),"status","COMPLETED"));}
  @PostMapping @Transactional public ApiResponse<Map<String,Object>> create(@Valid @RequestBody UserRequest q){requireRoleManage(q.role());String pwd=temp();db.update("insert into sys_user(username,password_hash,display_name,role,enabled,must_change_password) values(?,?,?,?,true,true)",q.username(),encoder.encode(pwd),q.displayName(),q.role());Long id=db.queryForObject("select last_insert_id()",Long.class);saveStations(id,q.role(),q.stationIds());audit.log("CREATE_USER","USER",id,null,Map.of("role",q.role()));return ApiResponse.ok(Map.of("id",id,"temporaryPassword",pwd));}
  @PutMapping("/{id}/enabled") public ApiResponse<Void> enabled(@PathVariable Long id,@RequestBody EnableRequest q){var current=SecurityUtils.current();String role=db.queryForObject("select role from sys_user where id=?",String.class,id);requireRoleManage(role);if(id.equals(current.id())&&!q.enabled())throw new BusinessException(400,"不能停用当前账号");if(!q.enabled()&&hasPendingTaskScores(id))throw new BusinessException(409,"该账号仍有未完成的任务评分，请先完成或转交后再停用");if("SUPER_ADMIN".equals(role)&&!q.enabled()&&db.queryForObject("select count(*) from sys_user where role='SUPER_ADMIN' and enabled=true",Integer.class)<=1)throw new BusinessException(400,"必须保留至少一个启用的超级管理员");db.update("update sys_user set enabled=?,version=version+1,security_version=security_version+1 where id=?",q.enabled(),id);audit.log("SET_USER_ENABLED","USER",id,Map.of("enabled",!q.enabled()),Map.of("enabled",q.enabled()));return ApiResponse.ok(null);}
  @PutMapping("/{id}/role") public ApiResponse<Void> role(@PathVariable Long id,@RequestBody Map<String,String> q){permissions.require(Permissions.USER_ADMIN_MANAGE);String role=q.get("role");if(!CHANGE_ROLES.contains(role))throw new BusinessException(400,"非法角色");String old=db.queryForObject("select role from sys_user where id=?",String.class,id);if(id.equals(SecurityUtils.current().id()))throw new BusinessException(400,"不能修改当前账号角色");boolean linkedEmployee=hasEmployeeProfile(id);if(linkedEmployee&&!"EMPLOYEE".equals(role))throw new BusinessException(400,"员工账号角色不可修改");if("EMPLOYEE".equals(role)&&!linkedEmployee)throw new BusinessException(400,"该账号未关联员工档案，不能设为员工角色");if("SUPER_ADMIN".equals(old)&&db.queryForObject("select count(*) from sys_user where role='SUPER_ADMIN' and enabled=true",Integer.class)<=1)throw new BusinessException(400,"必须保留至少一个超级管理员");db.update("update sys_user set role=?,version=version+1,security_version=security_version+1 where id=?",role,id);audit.log("CHANGE_ROLE","USER",id,Map.of("role",old),Map.of("role",role));return ApiResponse.ok(null);}
  @PutMapping("/{id}/display-name") @Transactional public ApiResponse<Void> displayName(@PathVariable Long id,@Valid @RequestBody DisplayNameRequest q){permissions.require(Permissions.USER_ADMIN_MANAGE);var before=db.queryForMap("select id,display_name from sys_user where id=?",id);db.update("update sys_user set display_name=?,version=version+1 where id=?",q.displayName(),id);if(hasEmployeeProfile(id))db.update("update employee set name=?,version=version+1 where user_id=?",q.displayName(),id);audit.log("CHANGE_DISPLAY_NAME","USER",id,before,Map.of("displayName",q.displayName()));return ApiResponse.ok(null);}
  @PutMapping("/{id}/username") @Transactional public ApiResponse<Void> username(@PathVariable Long id,@Valid @RequestBody UsernameRequest q){
    permissions.require(Permissions.USER_ADMIN_MANAGE);
    var before=db.queryForMap("select id,username,role from sys_user where id=?",id);
    if("SUPER_ADMIN".equals(before.get("role")))throw new BusinessException(403,"不能修改超级管理员账号的用户名");
    String username=q.username().trim();
    if(username.equals(before.get("username")))return ApiResponse.ok(null);
    db.update("update sys_user set username=?,version=version+1,security_version=security_version+1 where id=?",username,id);
    if(hasEmployeeProfile(id))db.update("update employee set employee_no=?,version=version+1 where user_id=?",username,id);
    audit.log("CHANGE_USERNAME","USER",id,before,Map.of("username",username));
    return ApiResponse.ok(null);
  }
  @PostMapping("/{id}/reset-password") public ApiResponse<Map<String,String>> reset(@PathVariable Long id){
    String role=db.queryForObject("select role from sys_user where id=?",String.class,id);
    requireRoleManage(role);
    String pwd=temp();
    db.update("update sys_user set password_hash=?,must_change_password=true,version=version+1,security_version=security_version+1 where id=?",encoder.encode(pwd),id);
    audit.log("RESET_PASSWORD","USER",id,null,null);
    return ApiResponse.ok(Map.of("temporaryPassword",pwd));
  }
  @PutMapping("/{id}/stations") @Transactional public ApiResponse<Void> stations(@PathVariable Long id,@RequestBody Map<String,List<Long>> q){String role=db.queryForObject("select role from sys_user where id=?",String.class,id);if(!"STATION_MANAGER".equals(role))throw new BusinessException(400,"只有服务站负责人需要设置服务站范围");requireRoleManage(role);saveStations(id,role,q.get("stationIds"));audit.log("SET_STATION_SCOPE","USER",id,null,q);return ApiResponse.ok(null);}
  private void validateBulkRequest(BulkRequest request){if(request==null||request.selection()==null||request.changes()==null||request.changes().isEmpty())throw new BusinessException(400,"请选择账号和至少一个修改字段");if(!Set.of("IDS","FILTER").contains(request.selection().mode()))throw new BusinessException(400,"非法选择方式");if("IDS".equals(request.selection().mode())&&(request.selection().ids()==null||request.selection().ids().isEmpty()))throw new BusinessException(400,"请选择至少一个账号");if(request.selection().ids()!=null&&request.selection().ids().size()>500)throw new BusinessException(400,"单次最多修改500个账号");if(request.changes().keySet().stream().anyMatch(key->!Set.of("enabled","role","stationIds").contains(key)))throw new BusinessException(400,"包含不支持的批量字段");}
  private List<Long> resolveBulkIds(BulkSelection selection){var allowed=allowedRoles(SecurityUtils.current());var args=new ArrayList<Object>(allowed);var marks=String.join(",",Collections.nCopies(allowed.size(),"?"));var where=new StringBuilder(" where u.role in ("+marks+")");if("IDS".equals(selection.mode())){var ids=new LinkedHashSet<>(selection.ids()==null?List.<Long>of():selection.ids());if(selection.excludedIds()!=null)ids.removeAll(selection.excludedIds());if(ids.isEmpty())throw new BusinessException(400,"没有可修改的账号");if(ids.size()>500)throw new BusinessException(400,"单次最多修改500个账号");where.append(" and u.id in (").append(String.join(",",Collections.nCopies(ids.size(),"?"))).append(")");args.addAll(ids);}else applyUserFilters(where,args,selection.filters());var rows=db.queryForList("select u.id from sys_user u left join employee e on e.user_id=u.id left join talent_batch b on b.id=e.batch_id left join business_unit bu on bu.id=e.business_unit_id"+where+" order by u.id",args.toArray());if(rows.isEmpty())throw new BusinessException(400,"筛选结果为空");if(rows.size()>500)throw new BusinessException(400,"单次最多修改500个账号，请缩小筛选范围");return rows.stream().map(row->((Number)row.get("id")).longValue()).toList();}
  private void applyUserFilters(StringBuilder where,List<Object> args,Map<String,Object> filters){if(filters==null)return;Object keyword=filters.get("keyword");if(keyword!=null&&!String.valueOf(keyword).isBlank()){where.append(" and (u.username like ? or u.display_name like ? or e.employee_no like ? or e.name like ? or b.name like ? or bu.name like ?)");String value="%"+String.valueOf(keyword).trim()+"%";for(int i=0;i<6;i++)args.add(value);}Object role=filters.get("role");if(role!=null&&!String.valueOf(role).isBlank()){where.append(" and u.role=?");args.add(role);}Object enabled=filters.get("enabled");if(enabled!=null&&!String.valueOf(enabled).isBlank()){where.append(" and u.enabled=?");args.add("enabled".equals(String.valueOf(enabled)));}addUserEquals(where,args,filters,"batchId","e.batch_id");addUserEquals(where,args,filters,"businessUnitId","e.business_unit_id");addUserEquals(where,args,filters,"classId","e.class_id");Object linked=filters.get("linked");if(linked!=null&&!String.valueOf(linked).isBlank())where.append("linked".equals(String.valueOf(linked))?" and e.id is not null":" and e.id is null");}
  private void addUserEquals(StringBuilder where,List<Object> args,Map<String,Object> filters,String key,String column){Object value=filters.get(key);if(value==null||String.valueOf(value).isBlank())return;where.append(" and ").append(column).append("=?");args.add(value);}
  private Map<Long,Integer> userVersions(List<Long> ids){var marks=String.join(",",Collections.nCopies(ids.size(),"?"));var rows=db.queryForList("select id,version from sys_user where id in ("+marks+") order by id",ids.toArray());if(rows.size()!=ids.size())throw new BusinessException(404,"部分账号不存在或无权访问");var result=new LinkedHashMap<Long,Integer>();rows.forEach(row->result.put(((Number)row.get("id")).longValue(),((Number)row.get("version")).intValue()));return result;}
  private String selectionHash(Map<Long,Integer> versions){try{var digest=MessageDigest.getInstance("SHA-256");var value=versions.entrySet().stream().map(entry->entry.getKey()+":"+entry.getValue()).reduce((a,b)->a+","+b).orElse("");return HexFormat.of().formatHex(digest.digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception error){throw new IllegalStateException(error);}}
  private void validateBulkChanges(List<Long> ids,BulkRequest request){var changes=request.changes();if(changes.containsKey("enabled")){permissions.require(Permissions.USER_EMPLOYEE_MANAGE);for(Long id:ids){String role=db.queryForObject("select role from sys_user where id=?",String.class,id);requireRoleManage(role);boolean enabled=Boolean.parseBoolean(String.valueOf(changes.get("enabled")));if(id.equals(SecurityUtils.current().id())&&!enabled)throw new BusinessException(400,"不能停用当前账号");if(!enabled&&hasPendingTaskScores(id))throw new BusinessException(409,"该账号仍有未完成的任务评分，请先完成或转交后再停用");if("SUPER_ADMIN".equals(role)&&!enabled&&db.queryForObject("select count(*) from sys_user where role='SUPER_ADMIN' and enabled=true",Integer.class)<=1)throw new BusinessException(400,"必须保留至少一个启用的超级管理员");}}
    if(changes.containsKey("role")){permissions.require(Permissions.USER_ADMIN_MANAGE);String target=String.valueOf(changes.get("role"));if(!CHANGE_ROLES.contains(target))throw new BusinessException(400,"非法角色");for(Long id:ids){String old=db.queryForObject("select role from sys_user where id=?",String.class,id);if(id.equals(SecurityUtils.current().id()))throw new BusinessException(400,"不能修改当前账号角色");boolean linked=hasEmployeeProfile(id);if(linked&&!"EMPLOYEE".equals(target))throw new BusinessException(400,"员工账号角色不可修改");if("EMPLOYEE".equals(target)&&!linked)throw new BusinessException(400,"该账号未关联员工档案，不能设为员工角色");if("SUPER_ADMIN".equals(old)&&db.queryForObject("select count(*) from sys_user where role='SUPER_ADMIN' and enabled=true",Integer.class)<=1)throw new BusinessException(400,"必须保留至少一个启用的超级管理员");}}
    if(changes.containsKey("stationIds")){permissions.require(Permissions.USER_OPS_ROLE_MANAGE);if(!(changes.get("stationIds") instanceof List<?> stationIds)||stationIds.isEmpty())throw new BusinessException(400,"服务站范围不能为空");for(Long id:ids){String role=db.queryForObject("select role from sys_user where id=?",String.class,id);if(!"STATION_MANAGER".equals(role))throw new BusinessException(400,"只有服务站负责人可以设置服务站范围");requireRoleManage(role);}}
  }
  private int countChanged(List<Long> ids,Map<String,Object> changes){var marks=String.join(",",Collections.nCopies(ids.size(),"?"));var rows=db.queryForList("select id,enabled,role from sys_user where id in ("+marks+")",ids.toArray());return (int)rows.stream().filter(row->(changes.containsKey("enabled")&&!Objects.equals(Boolean.valueOf(String.valueOf(row.get("enabled"))),Boolean.valueOf(String.valueOf(changes.get("enabled")))))||(changes.containsKey("role")&&!Objects.equals(String.valueOf(row.get("role")),String.valueOf(changes.get("role"))))||(changes.containsKey("stationIds")&&!stationScopeEquals(((Number)row.get("id")).longValue(),changes.get("stationIds")))).count();}
  private boolean stationScopeEquals(Long userId,Object value){var desired=((List<?>)value).stream().map(item->Long.valueOf(String.valueOf(item))).sorted().toList();var current=db.queryForList("select station_id from station_manager_scope where user_id=? order by station_id",Long.class,userId);return current.equals(desired);}
  private boolean updateBulkUser(Long id,BulkRequest request){var changes=request.changes();var before=db.queryForMap("select id,role,enabled from sys_user where id=? for update",id);boolean changed=false;if(changes.containsKey("enabled")){boolean enabled=Boolean.parseBoolean(String.valueOf(changes.get("enabled")));if(!Objects.equals(Boolean.valueOf(String.valueOf(before.get("enabled"))),enabled)){db.update("update sys_user set enabled=?,version=version+1,security_version=security_version+1 where id=?",enabled,id);if(request.syncLinkedEmployeeStatus()&&hasEmployeeProfile(id))db.update("update employee set status=?,version=version+1 where user_id=?",enabled?"ACTIVE":"INACTIVE",id);changed=true;}}if(changes.containsKey("role")){String role=String.valueOf(changes.get("role"));if(!Objects.equals(String.valueOf(before.get("role")),role)){db.update("update sys_user set role=?,version=version+1,security_version=security_version+1 where id=?",role,id);changed=true;}}if(changes.containsKey("stationIds")&&!stationScopeEquals(id,changes.get("stationIds"))){String role=String.valueOf(before.get("role"));saveStations(id,role,((List<?>)changes.get("stationIds")).stream().map(value->Long.valueOf(String.valueOf(value))).toList());db.update("update sys_user set version=version+1,security_version=security_version+1 where id=?",id);changed=true;}return changed;}
  private void ensureRequestNotUsed(String requestId,String action){if(requestId==null||requestId.isBlank())return;Integer count=db.queryForObject("select count(*) from operation_log where request_id=? and action=?",Integer.class,requestId,action);if(count!=null&&count>0)throw new BusinessException(409,"该批量请求已处理，请勿重复提交");}
  private List<String> allowedRoles(CurrentUser u){var roles=new ArrayList<String>();roles.add("EMPLOYEE");if(u.can(Permissions.USER_OPS_ROLE_MANAGE))roles.addAll(OPS_ROLES);if(u.can(Permissions.USER_ADMIN_MANAGE))roles.addAll(SYSTEM_ROLES);return roles;}
  private void requireRoleManage(String role){if("EMPLOYEE".equals(role))permissions.require(Permissions.USER_EMPLOYEE_MANAGE);else if(OPS_ROLES.contains(role))permissions.require(Permissions.USER_OPS_ROLE_MANAGE);else if(SYSTEM_ROLES.contains(role))permissions.require(Permissions.USER_ADMIN_MANAGE);else throw new BusinessException(400,"非法角色");}
  private boolean hasEmployeeProfile(Long id){Integer n=db.queryForObject("select count(*) from employee where user_id=?",Integer.class,id);return n!=null&&n>0;}
  private boolean hasPendingTaskScores(Long id){Integer n=db.queryForObject("select count(*) from task_reviewer_scope_member m join task_reviewer_scope rs on rs.id=m.scope_id and rs.status='ACTIVE' where m.reviewer_user_id=? and exists(select 1 from task_assignment a where a.scoring_scope_id=rs.id and a.status in ('NOT_SUBMITTED','PENDING_REVIEW','RETURNED'))",Integer.class,id);return n!=null&&n>0;}
  private void saveStations(Long id,String role,List<Long> ids){db.update("delete from station_manager_scope where user_id=?",id);if(!"STATION_MANAGER".equals(role))return;if(ids==null||ids.isEmpty())throw new BusinessException(400,"站长至少需要绑定一个服务站");for(Long stationId:new LinkedHashSet<>(ids))db.update("insert into station_manager_scope(user_id,station_id) values(?,?)",id,stationId);}
  private String temp(){return "Tmp"+(100000+random.nextInt(900000))+"!a";}
}
