package com.talent.platform.user;

import com.talent.platform.common.*;import com.talent.platform.security.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
import java.security.SecureRandom;import java.util.*;

@RestController @RequestMapping("/api/v1/users")
public class UserController {
  private static final List<String> OPS_ROLES=List.of("MENTOR","STATION_MANAGER","TRAINING_ADMIN");
  private static final List<String> SYSTEM_ROLES=List.of("ADMIN","SUPER_ADMIN");
  private final JdbcTemplate db;private final PasswordEncoder encoder;private final PermissionService permissions;private final AuditService audit;private final SecureRandom random=new SecureRandom();public UserController(JdbcTemplate db,PasswordEncoder encoder,PermissionService permissions,AuditService audit){this.db=db;this.encoder=encoder;this.permissions=permissions;this.audit=audit;}
  public record UserRequest(@NotBlank String username,@NotBlank String displayName,@Pattern(regexp="MENTOR|STATION_MANAGER|TRAINING_ADMIN|ADMIN") String role,List<Long> stationIds){}
  public record EnableRequest(boolean enabled){}
  @GetMapping public ApiResponse<List<Map<String,Object>>> list(@RequestParam(required=false)String role){permissions.require(Permissions.USER_EMPLOYEE_MANAGE);var u=SecurityUtils.current();var allowed=allowedRoles(u);if(role!=null&&!allowed.contains(role))return ApiResponse.ok(List.of());String marks=String.join(",",Collections.nCopies(allowed.size(),"?"));var args=new ArrayList<Object>(allowed);String where=" where u.role in ("+marks+")";if(role!=null){where+=" and u.role=?";args.add(role);}return ApiResponse.ok(db.queryForList("select u.id,u.username,u.display_name,u.role,u.enabled,u.must_change_password,u.created_at,group_concat(sms.station_id order by sms.station_id) station_ids,group_concat(s.name order by s.name separator '、') station_names from sys_user u left join station_manager_scope sms on sms.user_id=u.id left join service_station s on s.id=sms.station_id"+where+" group by u.id,u.username,u.display_name,u.role,u.enabled,u.must_change_password,u.created_at order by u.id desc",args.toArray()));}
  @PostMapping @Transactional public ApiResponse<Map<String,Object>> create(@Valid @RequestBody UserRequest q){requireRoleManage(q.role());String pwd=temp();db.update("insert into sys_user(username,password_hash,display_name,role,enabled,must_change_password) values(?,?,?,?,true,true)",q.username(),encoder.encode(pwd),q.displayName(),q.role());Long id=db.queryForObject("select last_insert_id()",Long.class);saveStations(id,q.role(),q.stationIds());audit.log("CREATE_USER","USER",id,null,Map.of("role",q.role()));return ApiResponse.ok(Map.of("id",id,"temporaryPassword",pwd));}
  @PutMapping("/{id}/enabled") public ApiResponse<Void> enabled(@PathVariable Long id,@RequestBody EnableRequest q){var current=SecurityUtils.current();String role=db.queryForObject("select role from sys_user where id=?",String.class,id);requireRoleManage(role);if(id.equals(current.id())&&!q.enabled())throw new BusinessException(400,"不能停用当前账号");if("SUPER_ADMIN".equals(role)&&!q.enabled()&&db.queryForObject("select count(*) from sys_user where role='SUPER_ADMIN' and enabled=true",Integer.class)<=1)throw new BusinessException(400,"必须保留至少一个启用的超级管理员");db.update("update sys_user set enabled=?,version=version+1,security_version=security_version+1 where id=?",q.enabled(),id);audit.log("SET_USER_ENABLED","USER",id,Map.of("enabled",!q.enabled()),Map.of("enabled",q.enabled()));return ApiResponse.ok(null);}
  @PutMapping("/{id}/role") public ApiResponse<Void> role(@PathVariable Long id,@RequestBody Map<String,String> q){permissions.require(Permissions.USER_ADMIN_MANAGE);String role=q.get("role");if(!List.of("MENTOR","STATION_MANAGER","TRAINING_ADMIN","ADMIN","SUPER_ADMIN").contains(role))throw new BusinessException(400,"非法角色");String old=db.queryForObject("select role from sys_user where id=?",String.class,id);if(id.equals(SecurityUtils.current().id()))throw new BusinessException(400,"不能修改当前账号角色");if("SUPER_ADMIN".equals(old)&&db.queryForObject("select count(*) from sys_user where role='SUPER_ADMIN' and enabled=true",Integer.class)<=1)throw new BusinessException(400,"必须保留至少一个超级管理员");db.update("update sys_user set role=?,version=version+1,security_version=security_version+1 where id=?",role,id);audit.log("CHANGE_ROLE","USER",id,Map.of("role",old),Map.of("role",role));return ApiResponse.ok(null);}
  @PostMapping("/{id}/reset-password") public ApiResponse<Map<String,String>> reset(@PathVariable Long id){String role=db.queryForObject("select role from sys_user where id=?",String.class,id);requireRoleManage(role);String pwd=temp();db.update("update sys_user set password_hash=?,must_change_password=true,version=version+1,security_version=security_version+1 where id=?",encoder.encode(pwd),id);audit.log("RESET_PASSWORD","USER",id,null,null);return ApiResponse.ok(Map.of("temporaryPassword",pwd));}
  @PutMapping("/{id}/stations") @Transactional public ApiResponse<Void> stations(@PathVariable Long id,@RequestBody Map<String,List<Long>> q){String role=db.queryForObject("select role from sys_user where id=?",String.class,id);if(!"STATION_MANAGER".equals(role))throw new BusinessException(400,"只有服务站负责人需要设置服务站范围");requireRoleManage(role);saveStations(id,role,q.get("stationIds"));audit.log("SET_STATION_SCOPE","USER",id,null,q);return ApiResponse.ok(null);}
  private List<String> allowedRoles(CurrentUser u){var roles=new ArrayList<String>();roles.add("EMPLOYEE");if(u.can(Permissions.USER_OPS_ROLE_MANAGE))roles.addAll(OPS_ROLES);if(u.can(Permissions.USER_ADMIN_MANAGE))roles.addAll(SYSTEM_ROLES);return roles;}
  private void requireRoleManage(String role){if("EMPLOYEE".equals(role))permissions.require(Permissions.USER_EMPLOYEE_MANAGE);else if(OPS_ROLES.contains(role))permissions.require(Permissions.USER_OPS_ROLE_MANAGE);else if(SYSTEM_ROLES.contains(role))permissions.require(Permissions.USER_ADMIN_MANAGE);else throw new BusinessException(400,"非法角色");}
  private void saveStations(Long id,String role,List<Long> ids){db.update("delete from station_manager_scope where user_id=?",id);if(!"STATION_MANAGER".equals(role))return;if(ids==null||ids.isEmpty())throw new BusinessException(400,"站长至少需要绑定一个服务站");for(Long stationId:new LinkedHashSet<>(ids))db.update("insert into station_manager_scope(user_id,station_id) values(?,?)",id,stationId);}
  private String temp(){return "Tmp"+(100000+random.nextInt(900000))+"!a";}
}
