package com.talent.platform.importer;

import com.alibaba.excel.EasyExcel;import com.talent.platform.common.*;import com.talent.platform.security.*;
import jakarta.servlet.http.HttpServletResponse;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
import java.net.URLEncoder;import java.nio.charset.StandardCharsets;import java.time.LocalDate;import java.util.*;

@RestController @RequestMapping("/api/v1/imports")
public class ImportController {
  private final JdbcTemplate db;private final PasswordEncoder encoder;private final PermissionService permissions;private final AuditService audit;public ImportController(JdbcTemplate db,PasswordEncoder encoder,PermissionService permissions,AuditService audit){this.db=db;this.encoder=encoder;this.permissions=permissions;this.audit=audit;}
  public record RowError(int row,String field,String message){} public record ImportResult(int imported,List<RowError> errors){}
  @GetMapping("/employees/template") public void template(HttpServletResponse response)throws Exception{permissions.require(Permissions.EMPLOYEE_WRITE);response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");response.setHeader("Content-Disposition","attachment; filename*=UTF-8''"+URLEncoder.encode("新员工导入模板.xlsx",StandardCharsets.UTF_8));var sample=new EmployeeImportRow();sample.setEmployeeNo("20260001");sample.setName("示例员工");sample.setBatch("2026届");sample.setBirthDate("2002-01-01");EasyExcel.write(response.getOutputStream(),EmployeeImportRow.class).sheet("新员工").doWrite(List.of(sample));}
  @PostMapping("/employees") @Transactional public ApiResponse<ImportResult> employees(@RequestParam MultipartFile file)throws Exception{permissions.require(Permissions.EMPLOYEE_WRITE);List<EmployeeImportRow> rows=EasyExcel.read(file.getInputStream()).head(EmployeeImportRow.class).sheet().doReadSync();var errors=new ArrayList<RowError>();var seen=new HashSet<String>();for(int i=0;i<rows.size();i++){var r=rows.get(i);int line=i+2;if(r.getEmployeeNo()==null||r.getEmployeeNo().isBlank())errors.add(new RowError(line,"工号","不能为空"));else if(!seen.add(r.getEmployeeNo())||!db.queryForList("select id from employee where employee_no=?",r.getEmployeeNo()).isEmpty())errors.add(new RowError(line,"工号","重复"));if(r.getName()==null||r.getName().isBlank())errors.add(new RowError(line,"姓名","不能为空"));if(id("talent_batch",r.getBatch())==null)errors.add(new RowError(line,"批次","不存在"));if(r.getStation()!=null&&!r.getStation().isBlank()&&id("service_station",r.getStation())==null)errors.add(new RowError(line,"服务站","不存在"));tryDate(r.getBirthDate(),line,"出生日期",errors);tryDate(r.getOnboardDate(),line,"入职日期",errors);}if(!errors.isEmpty())return ApiResponse.ok(new ImportResult(0,errors));for(var r:rows){db.update("insert into sys_user(username,password_hash,display_name,role,enabled,must_change_password) values(?,?,?,'EMPLOYEE',false,true)",r.getEmployeeNo(),encoder.encode(UUID.randomUUID().toString()),r.getName());Long uid=db.queryForObject("select last_insert_id()",Long.class);db.update("insert into employee(user_id,employee_no,name,batch_id,station_id,school,major,education,birth_date,native_place,residence,phone,onboard_date) values(?,?,?,?,?,?,?,?,?,?,?,?,?)",uid,r.getEmployeeNo(),r.getName(),id("talent_batch",r.getBatch()),id("service_station",r.getStation()),r.getSchool(),r.getMajor(),r.getEducation(),date(r.getBirthDate()),r.getNativePlace(),r.getResidence(),r.getPhone(),date(r.getOnboardDate()));}audit.log("IMPORT_EMPLOYEES","EMPLOYEE",null,null,Map.of("count",rows.size()));return ApiResponse.ok(new ImportResult(rows.size(),List.of()));}
  @GetMapping("/attendance/template") public void attendanceTemplate(HttpServletResponse response)throws Exception{permissions.require(Permissions.ATTENDANCE_MANAGE);response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");response.setHeader("Content-Disposition","attachment; filename*=UTF-8''"+URLEncoder.encode("签到导入模板.xlsx",StandardCharsets.UTF_8));var sample=new AttendanceImportRow();sample.setSessionId(1L);sample.setEmployeeNo("20260001");sample.setRemark("补录");EasyExcel.write(response.getOutputStream(),AttendanceImportRow.class).sheet("签到记录").doWrite(List.of(sample));}
  @PostMapping("/attendance") @Transactional public ApiResponse<ImportResult> attendance(@RequestParam MultipartFile file)throws Exception{permissions.require(Permissions.ATTENDANCE_MANAGE);List<AttendanceImportRow> rows=EasyExcel.read(file.getInputStream()).head(AttendanceImportRow.class).sheet().doReadSync();var errors=new ArrayList<RowError>();var user=SecurityUtils.current();var employeeIds=new ArrayList<Long>();for(int i=0;i<rows.size();i++){var r=rows.get(i);int line=i+2;Long eid=null;if(r.getSessionId()==null||db.queryForList("select id from course_session where id=?",r.getSessionId()).isEmpty())errors.add(new RowError(line,"场次ID","不存在"));if(r.getEmployeeNo()==null||r.getEmployeeNo().isBlank())errors.add(new RowError(line,"员工工号","不能为空"));else{var found=db.queryForList("select id from employee where employee_no=?",Long.class,r.getEmployeeNo());if(found.isEmpty())errors.add(new RowError(line,"员工工号","不存在"));else eid=found.get(0);}employeeIds.add(eid);}if(!errors.isEmpty())return ApiResponse.ok(new ImportResult(0,errors));for(int i=0;i<rows.size();i++){var r=rows.get(i);db.update("insert into attendance(session_id,employee_id,status,source,checked_at,operator_user_id,remark) values(?,?,'MANUAL','IMPORT',now(),?,?) on duplicate key update status='MANUAL',source='IMPORT',checked_at=now(),operator_user_id=values(operator_user_id),remark=values(remark)",r.getSessionId(),employeeIds.get(i),user.id(),r.getRemark());}audit.log("IMPORT_ATTENDANCE","ATTENDANCE",null,null,Map.of("count",rows.size()));return ApiResponse.ok(new ImportResult(rows.size(),List.of()));}
  private Long id(String table,String name){if(name==null||name.isBlank())return null;var x=db.queryForList("select id from "+table+" where name=?",Long.class,name);return x.isEmpty()?null:x.get(0);}
  private void tryDate(String value,int row,String field,List<RowError> errors){if(value!=null&&!value.isBlank())try{LocalDate.parse(value);}catch(Exception e){errors.add(new RowError(row,field,"格式应为 yyyy-MM-dd"));}}
  private LocalDate date(String value){return value==null||value.isBlank()?null:LocalDate.parse(value);}
}
