package com.talent.platform.course;

import com.talent.platform.common.*;import com.talent.platform.security.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;import java.security.SecureRandom;import java.time.*;import java.util.*;

@RestController @RequestMapping("/api/v1")
public class CourseController {
  private final JdbcTemplate db;private final PermissionService permissions;private final AuditService audit;private final SecureRandom random=new SecureRandom();public CourseController(JdbcTemplate db,PermissionService permissions,AuditService audit){this.db=db;this.permissions=permissions;this.audit=audit;}
  public record CourseRequest(@NotBlank String name,String description){}
  public record SessionRequest(@NotNull Long courseId,@NotBlank String title,String location,BigDecimal hours,@NotNull LocalDateTime startsAt,@NotNull LocalDateTime endsAt,@NotNull LocalDateTime checkinStartsAt,@NotNull LocalDateTime checkinEndsAt){}
  public record CheckinRequest(@Pattern(regexp="\\d{6}") String code){}
  public record ManualAttendanceRequest(@NotNull Long sessionId,@NotNull Long employeeId,String remark){}
  public record EnrollRequest(@NotEmpty List<Long> employeeIds){}
  @GetMapping("/courses") public ApiResponse<List<Map<String,Object>>> courses(){var u=SecurityUtils.current();if("EMPLOYEE".equals(u.role()))return ApiResponse.ok(db.queryForList("select distinct c.id,c.name,c.description from course c join course_session s on s.course_id=c.id join course_enrollment ce on ce.session_id=s.id join employee e on e.id=ce.employee_id where e.user_id=? and c.enabled=true order by c.id desc",u.id()));return ApiResponse.ok(db.queryForList("select c.id,c.name,c.description,c.created_at,u.display_name creator_name from course c join sys_user u on u.id=c.created_by where c.enabled=true order by c.id desc"));}
  @PostMapping("/courses") public ApiResponse<Long> create(@Valid @RequestBody CourseRequest q){permissions.require(Permissions.COURSE_MANAGE);var u=SecurityUtils.current();db.update("insert into course(name,description,created_by) values(?,?,?)",q.name(),q.description(),u.id());Long id=db.queryForObject("select last_insert_id()",Long.class);audit.log("CREATE_COURSE","COURSE",id,null,q);return ApiResponse.ok(id);}
  @GetMapping("/sessions") public ApiResponse<List<Map<String,Object>>> sessions(){var u=SecurityUtils.current();if("ALL".equals(u.dataScope()))return ApiResponse.ok(db.queryForList("select s.id,s.course_id,s.title,s.location,s.hours,s.starts_at,s.ends_at,s.checkin_starts_at,s.checkin_ends_at,s.checkin_code,c.name course_name from course_session s join course c on c.id=s.course_id order by s.starts_at desc"));var scope=permissions.employeeFilter("e");String sql="select distinct s.id,s.course_id,s.title,s.location,s.hours,s.starts_at,s.ends_at,s.checkin_starts_at,s.checkin_ends_at,c.name course_name from course_session s join course c on c.id=s.course_id join course_enrollment ce on ce.session_id=s.id join employee e on e.id=ce.employee_id where 1=1"+scope.sql()+" order by s.starts_at desc";return ApiResponse.ok(db.queryForList(sql,scope.args().toArray()));}
  @PostMapping("/sessions") public ApiResponse<Map<String,Object>> createSession(@Valid @RequestBody SessionRequest q){permissions.require(Permissions.COURSE_MANAGE);if(!q.endsAt().isAfter(q.startsAt())||!q.checkinEndsAt().isAfter(q.checkinStartsAt()))throw new BusinessException(400,"结束时间必须晚于开始时间");String code;do{code=String.format("%06d",random.nextInt(1_000_000));}while(!db.queryForList("select id from course_session where checkin_code=?",code).isEmpty());db.update("insert into course_session(course_id,title,location,hours,starts_at,ends_at,checkin_starts_at,checkin_ends_at,checkin_code,created_by) values(?,?,?,?,?,?,?,?,?,?)",q.courseId(),q.title(),q.location(),q.hours(),q.startsAt(),q.endsAt(),q.checkinStartsAt(),q.checkinEndsAt(),code,SecurityUtils.current().id());Long id=db.queryForObject("select last_insert_id()",Long.class);audit.log("CREATE_SESSION","SESSION",id,null,q);return ApiResponse.ok(Map.of("id",id,"checkinCode",code));}
  @PostMapping("/sessions/{id}/enroll") public ApiResponse<Integer> enroll(@PathVariable Long id,@Valid @RequestBody EnrollRequest q){permissions.require(Permissions.COURSE_MANAGE);int n=0;for(Long eid:new LinkedHashSet<>(q.employeeIds()))n+=db.update("insert ignore into course_enrollment(session_id,employee_id,assigned_by) values(?,?,?)",id,eid,SecurityUtils.current().id());audit.log("ENROLL_SESSION","SESSION",id,null,q);return ApiResponse.ok(n);}
  @PostMapping("/attendance/checkin") @PreAuthorize("hasRole('EMPLOYEE')") public ApiResponse<Void> checkin(@Valid @RequestBody CheckinRequest q){var u=SecurityUtils.current();var rows=db.queryForList("select id,checkin_starts_at,checkin_ends_at from course_session where checkin_code=?",q.code());if(rows.isEmpty())throw new BusinessException(404,"签到码无效");var s=rows.get(0);var now=LocalDateTime.now();LocalDateTime from=((java.sql.Timestamp)s.get("checkin_starts_at")).toLocalDateTime(),to=((java.sql.Timestamp)s.get("checkin_ends_at")).toLocalDateTime();if(now.isBefore(from)||now.isAfter(to))throw new BusinessException(400,"不在签到时间范围内");Long eid=db.queryForObject("select id from employee where user_id=?",Long.class,u.id());if(db.queryForObject("select count(*) from course_enrollment where session_id=? and employee_id=?",Integer.class,s.get("id"),eid)==0)throw new AccessDeniedException("未被安排参加该场次");db.update("insert into attendance(session_id,employee_id,status,source,checked_at,operator_user_id) values(?,?,'CHECKED_IN','SELF',?,?)",s.get("id"),eid,now,u.id());return ApiResponse.ok(null);}
  @PostMapping("/attendance/manual") public ApiResponse<Void> manual(@Valid @RequestBody ManualAttendanceRequest q){permissions.require(Permissions.ATTENDANCE_MANAGE);var u=SecurityUtils.current();db.update("insert into attendance(session_id,employee_id,status,source,checked_at,operator_user_id,remark) values(?,?,'MANUAL','MANUAL',now(),?,?) on duplicate key update status='MANUAL',source='MANUAL',checked_at=now(),operator_user_id=values(operator_user_id),remark=values(remark)",q.sessionId(),q.employeeId(),u.id(),q.remark());audit.log("MANUAL_ATTENDANCE","EMPLOYEE",q.employeeId(),null,q);return ApiResponse.ok(null);}
  @GetMapping("/attendance") public ApiResponse<List<Map<String,Object>>> attendance(@RequestParam(required=false)Long employeeId){if(employeeId!=null)permissions.requireEmployee(employeeId);var scope=permissions.employeeFilter("e");String where=" where 1=1"+scope.sql();var args=new ArrayList<Object>(scope.args());if(employeeId!=null){where+=" and e.id=?";args.add(employeeId);}return ApiResponse.ok(db.queryForList("select a.id,a.employee_id,a.status,a.source,a.checked_at,a.remark,e.name employee_name,s.title session_title,c.name course_name from attendance a join employee e on e.id=a.employee_id join course_session s on s.id=a.session_id join course c on c.id=s.course_id"+where+" order by a.checked_at desc limit 1000",args.toArray()));}
}
