package com.talent.platform.task;

import com.talent.platform.common.*;import com.talent.platform.security.*;import com.talent.platform.storage.FileStorageService;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
import java.time.LocalDateTime;import java.util.*;

@RestController @RequestMapping("/api/v1")
public class TaskController {
  private final JdbcTemplate db;private final FileStorageService storage;private final PermissionService permissions;private final AuditService audit;public TaskController(JdbcTemplate db,FileStorageService storage,PermissionService permissions,AuditService audit){this.db=db;this.storage=storage;this.permissions=permissions;this.audit=audit;}
  public record TaskRequest(@NotBlank String title,@NotBlank String description,String requirements,@NotNull LocalDateTime deadline){}
  public record AssignRequest(@NotNull Long taskId,List<Long> employeeIds,Long batchId,Long stationId){}
  public record ReviewRequest(@Pattern(regexp="APPROVE|RETURN") String decision,String comment,@Min(0) @Max(100) Integer score){}
  @GetMapping("/tasks") public ApiResponse<List<Map<String,Object>>> tasks(){var u=SecurityUtils.current();if("ALL".equals(u.dataScope()))return ApiResponse.ok(db.queryForList("select t.id,t.title,t.description,t.requirements,t.deadline,u.display_name creator_name,(select count(*) from task_assignment a where a.task_id=t.id) assigned_count from challenge_task t join sys_user u on u.id=t.created_by order by t.id desc"));var scope=permissions.employeeFilter("e");return ApiResponse.ok(db.queryForList("select distinct t.id,t.title,t.description,t.requirements,t.deadline from challenge_task t join task_assignment a on a.task_id=t.id join employee e on e.id=a.employee_id where 1=1"+scope.sql()+" order by t.id desc",scope.args().toArray()));}
  @PostMapping("/tasks") public ApiResponse<Long> create(@Valid @RequestBody TaskRequest q){permissions.require(Permissions.TASK_MANAGE);db.update("insert into challenge_task(title,description,requirements,deadline,created_by) values(?,?,?,?,?)",q.title(),q.description(),q.requirements(),q.deadline(),SecurityUtils.current().id());Long id=db.queryForObject("select last_insert_id()",Long.class);audit.log("CREATE_TASK","TASK",id,null,q);return ApiResponse.ok(id);}
  @PostMapping("/assignments/assign") @Transactional public ApiResponse<Integer> assign(@Valid @RequestBody AssignRequest q){permissions.require(Permissions.TASK_MANAGE);var u=SecurityUtils.current();var where=new StringBuilder(" where e.status='ACTIVE'");var p=new ArrayList<Object>();var groups=new ArrayList<String>();if(q.employeeIds()!=null&&!q.employeeIds().isEmpty()){groups.add("e.id in ("+String.join(",",Collections.nCopies(q.employeeIds().size(),"?"))+")");p.addAll(q.employeeIds());}if(q.batchId()!=null){groups.add("e.batch_id=?");p.add(q.batchId());}if(q.stationId()!=null){groups.add("e.station_id=?");p.add(q.stationId());}if(groups.isEmpty())throw new BusinessException(400,"请选择人员、批次或服务站");where.append(" and (").append(String.join(" or ",groups)).append(")");var ids=db.queryForList("select e.id from employee e"+where,Long.class,p.toArray());int n=0;for(Long id:ids)n+=db.update("insert ignore into task_assignment(task_id,employee_id,assigned_by) values(?,?,?)",q.taskId(),id,u.id());audit.log("ASSIGN_TASK","TASK",q.taskId(),null,Map.of("count",n));return ApiResponse.ok(n);}
  @GetMapping("/assignments") public ApiResponse<List<Map<String,Object>>> assignments(@RequestParam(required=false)String status){String where=" where 1=1";var scope=permissions.employeeFilter("e");where+=scope.sql();var p=new ArrayList<Object>(scope.args());if(status!=null&&!status.isBlank()){where+=" and a.status=?";p.add(status);}String sql="select a.*,t.title,t.description,t.requirements,t.deadline,e.name employee_name,e.employee_no,(select max(s.submission_version) from task_submission s where s.assignment_id=a.id) latest_version from task_assignment a join challenge_task t on t.id=a.task_id join employee e on e.id=a.employee_id"+where+" order by t.deadline,a.id desc";return ApiResponse.ok(db.queryForList(sql,p.toArray()));}
  @GetMapping("/assignments/{id}/submissions") public ApiResponse<List<Map<String,Object>>> submissions(@PathVariable Long id){assertAssignment(id,SecurityUtils.current(),false);var rows=db.queryForList("select s.*,u.display_name reviewer_name from task_submission s left join sys_user u on u.id=s.reviewed_by where s.assignment_id=? order by s.submission_version desc",id);for(var row:rows)row.put("files",db.queryForList("select id,original_name,size,content_type from stored_file where submission_id=?",row.get("id")));return ApiResponse.ok(rows);}
  @PostMapping(value="/assignments/{id}/submissions",consumes="multipart/form-data") @PreAuthorize("hasRole('EMPLOYEE')") @Transactional public ApiResponse<Long> submit(@PathVariable Long id,@RequestPart(required=false)String content,@RequestPart(required=false)List<MultipartFile> files){var u=SecurityUtils.current();assertAssignment(id,u,true);var a=db.queryForMap("select a.status,t.deadline from task_assignment a join challenge_task t on t.id=a.task_id where a.id=?",id);String status=String.valueOf(a.get("status"));if(!List.of("NOT_SUBMITTED","RETURNED").contains(status))throw new BusinessException(400,"当前状态不能提交");if(LocalDateTime.now().isAfter(((java.sql.Timestamp)a.get("deadline")).toLocalDateTime()))throw new BusinessException(400,"任务已截止");if((content==null||content.isBlank())&&(files==null||files.isEmpty()))throw new BusinessException(400,"请填写说明或上传成果文件");if(files!=null&&files.size()>5)throw new BusinessException(400,"单次最多上传5个文件");Integer version=db.queryForObject("select coalesce(max(submission_version),0)+1 from task_submission where assignment_id=?",Integer.class,id);db.update("insert into task_submission(assignment_id,submission_version,content) values(?,?,?)",id,version,content);Long sid=db.queryForObject("select last_insert_id()",Long.class);if(files!=null)for(MultipartFile file:files){validateFile(file);var o=storage.store(file);db.update("insert into stored_file(submission_id,original_name,content_type,size,storage_key,uploader_user_id) values(?,?,?,?,?,?)",sid,file.getOriginalFilename(),o.contentType(),o.size(),o.key(),u.id());}db.update("update task_assignment set status='PENDING_REVIEW',version=version+1 where id=?",id);return ApiResponse.ok(sid);}
  @PostMapping("/submissions/{id}/review") @Transactional public ApiResponse<Void> review(@PathVariable Long id,@Valid @RequestBody ReviewRequest q){permissions.require(Permissions.TASK_REVIEW);var u=SecurityUtils.current();var s=db.queryForMap("select s.assignment_id,s.status from task_submission s where s.id=?",id);Long aid=((Number)s.get("assignment_id")).longValue();if(!"PENDING_REVIEW".equals(s.get("status")))throw new BusinessException(400,"该版本已审核");if("APPROVE".equals(q.decision())&&q.score()==null)throw new BusinessException(400,"通过时必须评分");if("RETURN".equals(q.decision())&&(q.comment()==null||q.comment().isBlank()))throw new BusinessException(400,"退回时必须填写意见");String state="APPROVE".equals(q.decision())?"APPROVED":"RETURNED";db.update("update task_submission set status=?,reviewed_by=?,reviewed_at=now(),review_comment=?,score=? where id=?",state,u.id(),q.comment(),q.score(),id);db.update("update task_assignment set status=?,final_score=?,version=version+1 where id=?",state,"APPROVED".equals(state)?q.score():null,aid);audit.log("REVIEW_TASK","SUBMISSION",id,null,q);return ApiResponse.ok(null);}
  private void validateFile(MultipartFile f){if(f.isEmpty())throw new BusinessException(400,"不能上传空文件");String n=Optional.ofNullable(f.getOriginalFilename()).orElse("").toLowerCase();if(!n.matches(".*\\.(pdf|doc|docx|xls|xlsx|ppt|pptx|png|jpg|jpeg|zip)$"))throw new BusinessException(400,"不支持的文件类型: "+n);}
  private void assertAssignment(Long id,CurrentUser u,boolean employeeOnly){Long employeeId=db.queryForObject("select employee_id from task_assignment where id=?",Long.class,id);permissions.requireEmployee(employeeId);if(employeeOnly&&!"EMPLOYEE".equals(u.role()))throw new AccessDeniedException("仅员工本人可提交");}
}
