<script setup lang="ts">
import {nextTick,ref,watch} from 'vue';import {Refresh} from '@element-plus/icons-vue';import {api,type Envelope} from '@/api';import type {Overview} from './types';import PortraitHeader from './PortraitHeader.vue';import PortraitOverview from './PortraitOverview.vue';import PortraitCoursePanel from './PortraitCoursePanel.vue';import PortraitTaskPanel from './PortraitTaskPanel.vue';import PortraitExamPanel from './PortraitExamPanel.vue';import PortraitEvaluationPanel from './PortraitEvaluationPanel.vue';import PortraitStationPanel from './PortraitStationPanel.vue';import PortraitTimelinePanel from './PortraitTimelinePanel.vue';
const props=defineProps<{modelValue:boolean;employee:any}>();const emit=defineEmits<{(e:'update:modelValue',value:boolean):void;(e:'closed'):void}>();const active=ref('overview');const overview=ref<Overview|null>(null);const loading=ref(false);const error=ref('');const generation=ref(0);const refreshKey=ref(0);let controller:AbortController|undefined
async function loadOverview(){const id=props.employee?.id;if(!id)return;const current=++generation.value;controller?.abort();controller=new AbortController();loading.value=true;error.value='';overview.value=null;try{const r=await api.get<any,Envelope<Overview>>(`/employees/${id}/portrait/overview`,{signal:controller.signal,silentError:true} as any);if(current===generation.value)overview.value=r.data}catch(e:any){if(e?.code!=='ERR_CANCELED'&&current===generation.value)error.value=e?.response?.data?.message||'培养画像加载失败'}finally{if(current===generation.value)loading.value=false}}
function close(){generation.value++;controller?.abort();overview.value=null;error.value='';active.value='overview';emit('update:modelValue',false)}
function refresh(){if(active.value==='overview')loadOverview();else refreshKey.value++}
watch([()=>props.modelValue,()=>props.employee?.id],async([open])=>{if(open){active.value='overview';refreshKey.value++;await nextTick();loadOverview()}else{generation.value++;controller?.abort()}},{immediate:true})
</script>
<template><el-dialog :model-value="modelValue" width="88vw" top="20px" class="employee-portrait-dialog" :close-on-click-modal="false" destroy-on-close @close="close" @closed="emit('closed')">
  <template #header><div class="dialog-title"><span>人员培养画像</span><el-button :icon="Refresh" circle text title="刷新当前员工画像" @click="refresh"/></div></template>
  <div class="portrait-shell"><div class="portrait-summary"><PortraitHeader v-if="overview" :overview="overview"/><el-skeleton v-else-if="loading" :rows="2" animated/><el-alert v-else-if="error" type="error" :title="error" show-icon><template #default><el-button link type="primary" @click="loadOverview">重试</el-button></template></el-alert></div>
    <el-tabs v-model="active" class="portrait-tabs"><el-tab-pane label="培养概览" name="overview"><PortraitOverview v-if="overview" :overview="overview"/><el-empty v-else-if="!loading&&!error" description="暂无培养概览"/></el-tab-pane><el-tab-pane label="课程学习" name="courses" lazy><PortraitCoursePanel v-if="employee?.id" :key="`courses-${employee.id}-${refreshKey}`" :employee-id="employee.id"/></el-tab-pane><el-tab-pane label="闯关任务" name="tasks" lazy><PortraitTaskPanel v-if="employee?.id" :key="`tasks-${employee.id}-${refreshKey}`" :employee-id="employee.id"/></el-tab-pane><el-tab-pane label="考试成绩" name="exams" lazy><PortraitExamPanel v-if="employee?.id" :key="`exams-${employee.id}-${refreshKey}`" :employee-id="employee.id"/></el-tab-pane><el-tab-pane label="综合评价" name="evaluations" lazy><PortraitEvaluationPanel v-if="employee?.id" :key="`evaluations-${employee.id}-${refreshKey}`" :employee-id="employee.id"/></el-tab-pane><el-tab-pane label="服务站与位置" name="stations" lazy><PortraitStationPanel v-if="employee?.id" :key="`stations-${employee.id}-${refreshKey}`" :employee-id="employee.id"/></el-tab-pane><el-tab-pane label="成长记录" name="timeline" lazy><PortraitTimelinePanel v-if="employee?.id" :key="`timeline-${employee.id}-${refreshKey}`" :employee-id="employee.id"/></el-tab-pane></el-tabs>
  </div>
</el-dialog></template>
<style>.employee-portrait-dialog.el-dialog{width:min(88vw,1500px)!important;height:min(1000px,calc(100vh - 40px));margin:20px auto 0;display:flex;flex-direction:column;overflow:hidden;border-radius:12px}.employee-portrait-dialog .el-dialog__header{flex:0 0 auto;margin:0;padding:12px 18px;border-bottom:1px solid #e4e9f0}.employee-portrait-dialog .el-dialog__body{flex:1;min-height:0;padding:0;overflow:hidden}.employee-portrait-dialog .dialog-title{display:flex;align-items:center;gap:8px;font-size:16px;font-weight:700}.employee-portrait-dialog .portrait-shell{height:100%;display:grid;grid-template-rows:auto minmax(0,1fr);overflow:hidden}.employee-portrait-dialog .portrait-summary{min-height:86px;padding:12px 18px;border-bottom:1px solid #e4e9f0;background:#fbfcfe}.employee-portrait-dialog .portrait-tabs{min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr)}.employee-portrait-dialog .portrait-tabs>.el-tabs__header{margin:0;padding:0 18px}.employee-portrait-dialog .portrait-tabs>.el-tabs__content{min-height:0;overflow:auto;padding:14px 18px 18px}.employee-portrait-dialog .portrait-tabs>.el-tabs__content>.el-tab-pane{height:100%}@media(max-width:760px){.employee-portrait-dialog.el-dialog{width:calc(100vw - 16px)!important;height:calc(100vh - 16px);margin:8px auto 0}.employee-portrait-dialog .portrait-summary,.employee-portrait-dialog .portrait-tabs>.el-tabs__content{padding-left:10px;padding-right:10px}.employee-portrait-dialog .portrait-tabs>.el-tabs__header{padding:0 10px}}
</style>
