package com.talent.platform.employee;

import com.talent.platform.common.*;import com.talent.platform.security.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
import java.time.LocalDate;import java.util.*;

@RestController @RequestMapping("/api/v1/employees")
public class EmployeeController {
  private final JdbcTemplate db;private final PasswordEncoder encoder;private final PermissionService permissions;private final AuditService audit;public EmployeeController(JdbcTemplate db,PasswordEncoder encoder,PermissionService permissions,AuditService audit){this.db=db;this.encoder=encoder;this.permissions=permissions;this.audit=audit;}
  public record EmployeeRequest(@NotBlank String employeeNo,@NotBlank String name,Long batchId,Long stationId,Long mentorUserId,String school,String major,String education,LocalDate birthDate,String nativePlace,String residence,String phone,LocalDate onboardDate){}
  public record BindRequest(@NotEmpty List<Long> employeeIds,@NotNull Long mentorUserId){}
  @GetMapping public ApiResponse<PageResult<Map<String,Object>>> list(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String keyword,@RequestParam(required=false)Long batchId,@RequestParam(required=false)Long stationId,@RequestParam(required=false)Long mentorId){
    permissions.require(Permissions.EMPLOYEE_READ);var u=SecurityUtils.current();var where=new StringBuilder(" where 1=1");var p=new ArrayList<Object>();var scope=permissions.employeeFilter("e");where.append(scope.sql());p.addAll(scope.args());
    if(keyword!=null&&!keyword.isBlank()){where.append(" and (e.name like ? or e.employee_no like ?)");p.add("%"+keyword+"%");p.add("%"+keyword+"%");}if(batchId!=null){where.append(" and e.batch_id=?");p.add(batchId);}if(stationId!=null){where.append(" and e.station_id=?");p.add(stationId);}if(mentorId!=null&&SecurityUtils.admin(u)){where.append(" and e.mentor_user_id=?");p.add(mentorId);}
    long total=db.queryForObject("select count(*) from employee e"+where,Long.class,p.toArray());p.add(Math.min(size,100));p.add(Math.max(0,(page-1)*size));
    String sql="select e.*,b.name batch_name,s.name station_name,m.display_name mentor_name from employee e left join talent_batch b on b.id=e.batch_id left join service_station s on s.id=e.station_id left join sys_user m on m.id=e.mentor_user_id"+where+" order by e.id desc limit ? offset ?";
    return ApiResponse.ok(new PageResult<>(db.queryForList(sql,p.toArray()),total,page,size));
  }
  @PostMapping @Transactional public ApiResponse<Long> create(@Valid @RequestBody EmployeeRequest q){permissions.require(Permissions.EMPLOYEE_WRITE);
    db.update("insert into sys_user(username,password_hash,display_name,role,enabled,must_change_password) values(?,?,?,'EMPLOYEE',false,true)",q.employeeNo(),encoder.encode(UUID.randomUUID().toString()),q.name());Long uid=db.queryForObject("select last_insert_id()",Long.class);
    db.update("insert into employee(user_id,employee_no,name,batch_id,station_id,mentor_user_id,school,major,education,birth_date,native_place,residence,phone,onboard_date) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",uid,q.employeeNo(),q.name(),q.batchId(),q.stationId(),q.mentorUserId(),q.school(),q.major(),q.education(),q.birthDate(),q.nativePlace(),q.residence(),q.phone(),q.onboardDate());Long id=db.queryForObject("select last_insert_id()",Long.class);audit.log("CREATE_EMPLOYEE","EMPLOYEE",id,null,q);return ApiResponse.ok(id);
  }
  @PutMapping("/{id}") @Transactional public ApiResponse<Void> update(@PathVariable Long id,@Valid @RequestBody EmployeeRequest q){permissions.require(Permissions.EMPLOYEE_WRITE);var before=db.queryForMap("select * from employee where id=?",id);Long uid=((Number)before.get("user_id")).longValue();db.update("update employee set employee_no=?,name=?,batch_id=?,station_id=?,mentor_user_id=?,school=?,major=?,education=?,birth_date=?,native_place=?,residence=?,phone=?,onboard_date=?,version=version+1 where id=?",q.employeeNo(),q.name(),q.batchId(),q.stationId(),q.mentorUserId(),q.school(),q.major(),q.education(),q.birthDate(),q.nativePlace(),q.residence(),q.phone(),q.onboardDate(),id);db.update("update sys_user set username=?,display_name=?,version=version+1,security_version=security_version+1 where id=?",q.employeeNo(),q.name(),uid);audit.log("UPDATE_EMPLOYEE","EMPLOYEE",id,before,q);return ApiResponse.ok(null);}
  @PostMapping("/bind-mentor") public ApiResponse<Integer> bind(@Valid @RequestBody BindRequest q){permissions.require(Permissions.EMPLOYEE_WRITE);Integer mentor=db.queryForObject("select count(*) from sys_user where id=? and role='MENTOR' and enabled=true",Integer.class,q.mentorUserId());if(mentor==null||mentor==0)throw new BusinessException(400,"导师账号不存在或未启用");String marks=String.join(",",Collections.nCopies(q.employeeIds().size(),"?"));var args=new ArrayList<Object>();args.add(q.mentorUserId());args.addAll(q.employeeIds());int n=db.update("update employee set mentor_user_id=?,version=version+1 where id in ("+marks+")",args.toArray());audit.log("BIND_MENTOR","EMPLOYEE",null,null,q);return ApiResponse.ok(n);}
  @GetMapping("/{id}") public ApiResponse<Map<String,Object>> detail(@PathVariable Long id){permissions.require(Permissions.EMPLOYEE_READ);permissions.requireEmployee(id);return ApiResponse.ok(db.queryForMap("select e.*,b.name batch_name,s.name station_name,m.display_name mentor_name from employee e left join talent_batch b on b.id=e.batch_id left join service_station s on s.id=e.station_id left join sys_user m on m.id=e.mentor_user_id where e.id=?",id));}
}
