<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,type Envelope} from '@/api'
import {useAuthStore} from '@/stores/auth'

type Batch=Record<string,any>
const auth=useAuthStore(),type=ref<'EXAM'|'EVALUATION'>('EXAM'),sourceSystem=ref('历史系统'),batches=ref<Batch[]>([]),selected=ref<Batch>(),loading=ref(false),detailLoading=ref(false)
const canPublish=computed(()=>['ADMIN','SUPER_ADMIN'].includes(auth.user?.role||''))
async function load(){loading.value=true;try{batches.value=(await api.get<any,Envelope<Batch[]>>('/history-imports')).data}catch{}finally{loading.value=false}}
async function template(){const response=await api.get<any,Blob>('/history-imports/templates',{params:{type:type.value},responseType:'blob'});const url=URL.createObjectURL(response);const a=document.createElement('a');a.href=url;a.download=`历史${type.value==='EXAM'?'考试成绩':'综合评价'}导入模板.xlsx`;a.click();URL.revokeObjectURL(url)}
async function upload(file:File){const form=new FormData();form.append('type',type.value);form.append('sourceSystem',sourceSystem.value.trim()||'历史系统');form.append('file',file);const result=(await api.post<any,Envelope<any>>('/history-imports',form)).data;ElMessage.success(`已创建导入批次，${result.rowCount} 行，错误 ${result.errorCount} 条`);await load();await open(result.batchId);return false}
async function open(id:number){detailLoading.value=true;try{selected.value=(await api.get<any,Envelope<Batch>>(`/history-imports/${id}`)).data}catch{}finally{detailLoading.value=false}}
async function validate(){if(!selected.value)return;await api.post(`/history-imports/${selected.value.id}/validate`);ElMessage.success('已重新校验');await open(selected.value.id);await load()}
async function submit(){if(!selected.value)return;await api.post(`/history-imports/${selected.value.id}/submit`);ElMessage.success('已提交审核');await open(selected.value.id);await load()}
async function publish(){if(!selected.value)return;await ElMessageBox.confirm('发布后历史数据将进入成绩中心和培养画像，并保持只读。确认发布吗？','审核发布',{type:'warning'});await api.post(`/history-imports/${selected.value.id}/publish`);ElMessage.success('历史数据已发布');await open(selected.value.id);await load()}
async function revoke(){if(!selected.value)return;await ElMessageBox.confirm('撤销后该批次数据将不再对业务页面可见。确认撤销吗？','撤销批次',{type:'warning'});await api.post(`/history-imports/${selected.value.id}/revoke`);ElMessage.success('批次已撤销');await open(selected.value.id);await load()}
async function addManualRow(){if(!selected.value)return;const raw=(await ElMessageBox.prompt('请输入一行 JSON 数据；字段名请按导入模板填写','人工补录',{inputType:'textarea',inputValue:type.value==='EXAM'?'{"externalExamKey":"","employeeNo":"","resultStatus":"COMPLETED","score":""}':'{"employeeNo":"","summaryType":"MONTH","periodKey":"","finalScore":""}'})).value;try{const data=JSON.parse(raw);const rowType=type.value==='EXAM'?'EXAM_RESULT':'EVALUATION';await api.post(`/history-imports/${selected.value.id}/rows`,{rowType,data});ElMessage.success('已新增待校验行');await open(selected.value.id);await load()}catch{ElMessage.error('JSON 格式不正确，未保存')}}
async function editRow(row:any){if(!selected.value||selected.value.status==='PUBLISHED')return;const raw=(await ElMessageBox.prompt('修改该行 JSON 数据','修正导入行',{inputType:'textarea',inputValue:row.raw_json||'{}'})).value;try{await api.put(`/history-imports/${selected.value.id}/rows/${row.id}`,JSON.parse(raw));ElMessage.success('已保存修改并重新校验');await open(selected.value.id);await load()}catch{ElMessage.error('JSON 格式不正确，未保存')}}
function state(row:any){return row.state==='ERROR'?{label:'错误',type:'danger'}:row.state==='WARNING'?{label:'警告',type:'warning'}:{label:'通过',type:'success'}}
onMounted(load)
</script>

<template>
  <div class="history-page">
    <header class="page-head"><div><span class="eyebrow">数据管理 · 历史成绩</span><h1>历史成绩与综合评价导入</h1><p>线下考试和历史评价先校验、再审核发布；发布后记录只读。</p></div><div class="head-actions"><el-select v-model="type" filterable style="width:150px"><el-option label="历史考试成绩" value="EXAM"/><el-option label="历史综合评价" value="EVALUATION"/></el-select><el-input v-model="sourceSystem" placeholder="来源系统" style="width:150px"/><el-button @click="template">下载模板</el-button><el-upload :show-file-list="false" :before-upload="upload" accept=".xlsx,.xls"><el-button type="primary">上传 Excel</el-button></el-upload></div></header>
    <div class="history-layout">
      <el-card class="batch-card"><template #header><div class="card-head"><strong>导入批次</strong><el-button link @click="load">刷新</el-button></div></template><el-table :data="batches" v-loading="loading" row-key="id" highlight-current-row @row-click="(row:Batch)=>open(row.id)"><el-table-column prop="id" label="#" width="62"/><el-table-column prop="import_type" label="类型" width="100"><template #default="s">{{s.row.import_type==='EXAM'?'考试成绩':'综合评价'}}</template></el-table-column><el-table-column prop="source_system" label="来源" min-width="110"/><el-table-column prop="original_filename" label="文件" min-width="150" show-overflow-tooltip/><el-table-column prop="status" label="状态" width="90"/><el-table-column prop="created_at" label="创建时间" width="150"/></el-table><el-empty v-if="!loading&&!batches.length" description="暂无导入批次"/></el-card>
      <el-card class="detail-card" v-loading="detailLoading"><template #header><div class="card-head"><strong>批次预览</strong><div v-if="selected" class="detail-actions"><el-button @click="addManualRow" :disabled="!['DRAFT','SUBMITTED'].includes(selected.status)">人工补录</el-button><el-button @click="validate" :disabled="!['DRAFT','SUBMITTED'].includes(selected.status)">重新校验</el-button><el-button @click="submit" type="primary" plain :disabled="selected.error_count>0||!['DRAFT','SUBMITTED'].includes(selected.status)">提交审核</el-button><el-button v-if="canPublish" @click="publish" type="success" :disabled="selected.error_count>0||!['DRAFT','SUBMITTED'].includes(selected.status)">发布</el-button><el-button v-if="canPublish" @click="revoke" type="danger" plain :disabled="selected.status!=='PUBLISHED'">撤销</el-button></div></div></template><el-empty v-if="!selected" description="请选择左侧批次"/><template v-else><div class="summary"><span>总行数 <b>{{selected.row_count}}</b></span><span>通过 <b class="ok">{{selected.valid_count}}</b></span><span>错误 <b class="bad">{{selected.error_count}}</b></span><span>警告 <b class="warn">{{selected.warning_count}}</b></span><span>状态 <el-tag>{{selected.status}}</el-tag></span></div><el-alert v-if="selected.status==='PUBLISHED'" title="已发布批次为只读；如需修正请重新导入新版本。" type="success" :closable="false"/><el-table :data="selected.rows" height="520" stripe><el-table-column prop="sheet_name" label="页签" width="100"/><el-table-column prop="row_no" label="行号" width="70"/><el-table-column prop="row_type" label="数据类型" width="150"/><el-table-column prop="employee_no" label="工号" width="110"/><el-table-column label="校验状态" width="90"><template #default="s"><el-tag :type="state(s.row).type" effect="plain">{{state(s.row).label}}</el-tag></template></el-table-column><el-table-column prop="error_message" label="错误" min-width="220" show-overflow-tooltip/><el-table-column prop="warning_message" label="警告" min-width="220" show-overflow-tooltip/><el-table-column label="操作" width="70"><template #default="s"><el-button link type="primary" :disabled="selected.status==='PUBLISHED'" @click="editRow(s.row)">修正</el-button></template></el-table-column></el-table></template></el-card>
    </div>
  </div>
</template>

<style scoped>
.history-page{padding:26px 28px;background:#f6f8fb;min-height:calc(100vh - 64px)}.page-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:18px}.eyebrow{font-size:12px;color:#3678c7;font-weight:700}.page-head h1{margin:7px 0 0;color:#263247;font-size:25px}.page-head p{margin:7px 0 0;color:#7d899a;font-size:13px}.head-actions{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.history-layout{display:grid;grid-template-columns:minmax(330px,.8fr) minmax(520px,1.6fr);gap:16px}.batch-card,.detail-card{border:1px solid #e5eaf1}.card-head{display:flex;justify-content:space-between;align-items:center}.detail-actions{display:flex;gap:8px}.summary{display:flex;gap:20px;align-items:center;padding:0 0 14px;color:#7d899a;font-size:13px;flex-wrap:wrap}.summary b{color:#263247;font-size:18px}.summary .ok{color:#43a047}.summary .bad{color:#e05260}.summary .warn{color:#d88a1d}.detail-card :deep(.el-alert){margin-bottom:12px}@media(max-width:1000px){.page-head{flex-direction:column}.history-layout{grid-template-columns:1fr}.batch-card{min-height:260px}}@media(max-width:640px){.history-page{padding:16px}.head-actions>*{width:100%!important}.detail-actions{flex-wrap:wrap}.detail-actions>*{flex:1}}
</style>
